### ISSUE TITLE
Only for Chromium, no support for Firefox

### ISSUE THREAD

**Issue by ImTani** [ivedmohan/BlockHub#22]
The extension seems to only work on chromium-based web browsers, and not for firefox based browsers.

**Comment by ivedmohan** [comment]
> The extension seems to only work on chromium-based web browsers, and not for firefox based browsers.

@ImTani what will you be working then ?

**Comment by ImTani** [comment]
> > The extension seems to only work on chromium-based web browsers, and not for firefox based browsers.
> 
> @ImTani what will you be working then ? 

I've made the updates, pushing soon.

**Comment by ivedmohan** [comment]
Thanks for this issue
